---
version: "3"
services:
  kitana:
    hostname: "kitana"
    container_name: "kitana"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "pannal/kitana:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/kitana:/app/data:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.kitana-rtr.entrypoints=https"
      - "traefik.http.routers.kitana-rtr.rule=Host(`kitana.${DOMAIN}`)"
      - "traefik.http.routers.kitana-rtr.tls=true"
      - "traefik.http.routers.kitana-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.kitana-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.kitana-rtr.service=kitana-svc"
      - "traefik.http.services.kitana-svc.loadbalancer.server.port=31337"
networks:
  proxy:
    driver: bridge
    external: true
